-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.account
(
    id integer NOT NULL,
    name character varying(100) NOT NULL,
    "position" character varying(100),
    username character varying(100) NOT NULL,
    password character varying(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.area
(
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    description text,
    PRIMARY KEY (id)
);

CREATE TABLE public.area_warehouse
(
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    type level_important NOT NULL,
    date_default timestamp without time zone NOT NULL,
    date_optional timestamp without time zone,
    description text,
    warehouse_class_id integer,
    area_id integer,
    PRIMARY KEY (id)
);

CREATE TABLE public.building
(
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    coordinate geometry,
    description text,
    target_id integer,
    PRIMARY KEY (id)
);

CREATE TABLE public.category
(
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    information text,
    category_id integer,
    area_id integer,
    PRIMARY KEY (id)
);

CREATE TABLE public.category_warehouse
(
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    type level_important NOT NULL,
    date_default timestamp without time zone NOT NULL,
    date_optional timestamp without time zone,
    description text,
    warehouse_class_id integer,
    category_id integer,
    PRIMARY KEY (id)
);

CREATE TABLE public.file_store
(
    id integer NOT NULL,
    file character varying(500) NOT NULL,
    area_warehouse_id integer,
    category_warehouse_id integer,
    target_warehouse_id integer,
    information_id integer,
    image_id integer,
    PRIMARY KEY (id)
);

CREATE TABLE public.image
(
    id integer NOT NULL,
    name character varying(255),
    datetime timestamp without time zone NOT NULL,
    resolution character varying(100),
    description text,
    target_id integer,
    PRIMARY KEY (id)
);

CREATE TABLE public.information
(
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    date_default timestamp without time zone NOT NULL,
    date_optional timestamp without time zone,
    description text,
    coordinate geometry,
    boundary geometry,
    information_class_id integer,
    target_id integer,
    category_id integer,
    PRIMARY KEY (id)
);

CREATE TABLE public.information_class
(
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    description text,
    PRIMARY KEY (id)
);

CREATE TABLE public.report
(
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    date timestamp without time zone NOT NULL,
    "number" character varying(100) NOT NULL,
    account_id integer,
    target_id integer,
    category_id integer,
    PRIMARY KEY (id)
);

CREATE TABLE public.spatial_ref_sys
(
    srid integer NOT NULL,
    auth_name character varying(256),
    auth_srid integer,
    srtext character varying(2048),
    proj4text character varying(2048),
    PRIMARY KEY (srid)
);

CREATE TABLE public.target
(
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    coordinate geometry,
    boundary geometry,
    date_created timestamp without time zone,
    type target_class NOT NULL,
    icon character varying(255),
    general_information text,
    target_id integer,
    PRIMARY KEY (id)
);

CREATE TABLE public.target_category
(
    id integer NOT NULL,
    target_id integer NOT NULL,
    category_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.target_warehouse
(
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    type level_important NOT NULL,
    date_default timestamp without time zone NOT NULL,
    date_optional timestamp without time zone,
    description text,
    warehouse_class_id integer,
    target_id integer,
    PRIMARY KEY (id)
);

CREATE TABLE public.warehouse_class
(
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    description text,
    PRIMARY KEY (id)
);

ALTER TABLE public.area_warehouse
    ADD FOREIGN KEY (area_id)
    REFERENCES public.area (id)
    NOT VALID;


ALTER TABLE public.area_warehouse
    ADD FOREIGN KEY (warehouse_class_id)
    REFERENCES public.warehouse_class (id)
    NOT VALID;


ALTER TABLE public.building
    ADD FOREIGN KEY (target_id)
    REFERENCES public.target (id)
    NOT VALID;


ALTER TABLE public.category
    ADD FOREIGN KEY (area_id)
    REFERENCES public.area (id)
    NOT VALID;


ALTER TABLE public.category
    ADD FOREIGN KEY (category_id)
    REFERENCES public.category (id)
    NOT VALID;


ALTER TABLE public.category_warehouse
    ADD FOREIGN KEY (category_id)
    REFERENCES public.category (id)
    NOT VALID;


ALTER TABLE public.category_warehouse
    ADD FOREIGN KEY (warehouse_class_id)
    REFERENCES public.warehouse_class (id)
    NOT VALID;


ALTER TABLE public.file_store
    ADD FOREIGN KEY (area_warehouse_id)
    REFERENCES public.area_warehouse (id)
    NOT VALID;


ALTER TABLE public.file_store
    ADD FOREIGN KEY (category_warehouse_id)
    REFERENCES public.category_warehouse (id)
    NOT VALID;


ALTER TABLE public.file_store
    ADD FOREIGN KEY (image_id)
    REFERENCES public.image (id)
    NOT VALID;


ALTER TABLE public.file_store
    ADD FOREIGN KEY (information_id)
    REFERENCES public.information (id)
    NOT VALID;


ALTER TABLE public.file_store
    ADD FOREIGN KEY (target_warehouse_id)
    REFERENCES public.target_warehouse (id)
    NOT VALID;


ALTER TABLE public.image
    ADD FOREIGN KEY (target_id)
    REFERENCES public.target (id)
    NOT VALID;


ALTER TABLE public.information
    ADD FOREIGN KEY (category_id)
    REFERENCES public.category (id)
    NOT VALID;


ALTER TABLE public.information
    ADD FOREIGN KEY (information_class_id)
    REFERENCES public.information_class (id)
    NOT VALID;


ALTER TABLE public.information
    ADD FOREIGN KEY (target_id)
    REFERENCES public.target (id)
    NOT VALID;


ALTER TABLE public.report
    ADD FOREIGN KEY (account_id)
    REFERENCES public.account (id)
    NOT VALID;


ALTER TABLE public.report
    ADD FOREIGN KEY (category_id)
    REFERENCES public.category (id)
    NOT VALID;


ALTER TABLE public.report
    ADD FOREIGN KEY (target_id)
    REFERENCES public.target (id)
    NOT VALID;


ALTER TABLE public.target
    ADD FOREIGN KEY (target_id)
    REFERENCES public.target (id)
    NOT VALID;


ALTER TABLE public.target_category
    ADD FOREIGN KEY (category_id)
    REFERENCES public.category (id)
    NOT VALID;


ALTER TABLE public.target_category
    ADD FOREIGN KEY (target_id)
    REFERENCES public.target (id)
    NOT VALID;


ALTER TABLE public.target_warehouse
    ADD FOREIGN KEY (target_id)
    REFERENCES public.target (id)
    NOT VALID;


ALTER TABLE public.target_warehouse
    ADD FOREIGN KEY (warehouse_class_id)
    REFERENCES public.warehouse_class (id)
    NOT VALID;

END;